# -*- coding: utf-8 -*-
"""Customer Intent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cwazgDxuiX8q4jHFYWC60_DzehXRbBS5
"""

import pandas as pd

df = pd.read_csv("Bitext_Sample_Customer_Service_Testing_Dataset.csv")
df.head()

df.intent.value_counts()
df.isnull().sum()

import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z ]', '', text)
    return text

df['clean_text'] = df['utterance'].apply(clean_text)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df['clean_text'],
    df['intent'],
    test_size=0.2,
    random_state=42,
    stratify=df['intent']
)

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2)
)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train_vec, y_train)

from sklearn.metrics import classification_report

y_pred = model.predict(X_test_vec)
print(classification_report(y_test, y_pred))

import joblib

joblib.dump(model, "intent_model.pkl")
joblib.dump(vectorizer, "tfidf.pkl")